CREATE TABLE Usuario (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    online BOOLEAN DEFAULT FALSE
);

-- Tabla Mensaje
CREATE TABLE Mensaje (
    id INT PRIMARY KEY AUTO_INCREMENT,
    de INT NOT NULL,
    para INT NOT NULL,
    mensaje TEXT NOT NULL,
    created_at TIMESTAMP(0) NOT NULL,
    updated_at TIMESTAMP(0) NOT NULL,
    FOREIGN KEY (de) REFERENCES Usuario(id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (para) REFERENCES Usuario(id) ON UPDATE CASCADE ON DELETE CASCADE
);